### ISSUE TITLE
Magento 2 Headless Integration

### ISSUE THREAD

**Issue by SamTaal** [wexo/module-webshipper#1]
Hi,

Currently I'm implementing this module for one of our webshops in combination with a headless website and a Magento back-end. Now when setting the shipping address through the REST API (POST /shipping-information) we are getting a response with legit data. When paying (POST /payment-information) we are getting an error there's no shipping method in the cart.

I think we need more values in our extension_attributes, so webshipper can actually calculate some stuff, but there's no documentation whatsoever and can't really figure out by reading the code of this module. Is there any way of even implementing Webshipper in combination with headless?

For you information, we are running Magento 2.4.3-p1.

Thanks in advance.
Sam

**Comment by WebKenth** [comment]
@UniqueNL  

Firstly i'd recommend you update your magento to 2.4.3-p3 as it is a security patch and you are behind by 2 versions leaving you exposed to potential threats( https://devdocs.magento.com/guides/v2.4/release-notes/2-4-3-p3.html )

This module is merely sending requests to Webshipper via `collectRates` methods in magento

In base magento you have to select a shipping method before you go to see available payment methods.

How do you fetch your shipping methods? 

The extensions attributes part of this module is only for passing the data from webshipper specific information like droppoint from quote to order and it can then be retrieved further down the line if required.



Without further information on how your frontend attempts to communicate with magento i cannot help you

It is also not the modules responsibility to handle this kind of functionality ;) 

I found this method in `magento/module-quote` vendor/magento/module-quote/Model/Quote/Address.php:1022 
which constructs a request and collects all rates available for the quote (vendor/magento/module-quote/Model/Quote/Address.php:1077)

Maybe this will help you achieve your goal?
