### ISSUE TITLE
This check for in_array causes errors

### ISSUE THREAD

**Issue by pepijnblom** [wexo/module-webshipper#2]
https://github.com/wexo/module-webshipper/blob/254f3a40bfac2748eaec0b6686c2ceff810c869b/Observer/ExportOrderAtStatus.php#L43

`$exportAtOrderStatus` is a string if only one value is selected in admin:
![image](https://user-images.githubusercontent.com/6009489/204244348-fcd15f0c-f881-4bb3-abb4-02498ba13f8e.png)
![image](https://user-images.githubusercontent.com/6009489/204244469-739674c2-d0a2-4922-ad6d-eafece3d28a8.png)
![image](https://user-images.githubusercontent.com/6009489/204244569-de1f748d-92d1-4e20-9b24-a05d1d467b71.png)

**Comment by WebKenth** [comment]
https://github.com/wexo/module-webshipper/blob/1.0.0/Model/Config.php#L113
![image](https://user-images.githubusercontent.com/13419123/231149842-a862f4ad-02de-46a6-8e94-4714033cb9ca.png)


If the configuration is a string it gets converted to an array :)

**Comment by pepijnblom** [comment]
For anyone running into this here's a patch.. Sentry was not throwing this error for no reason..

```
Index: vendor/wexo/module-webshipper/Observer/ExportOrderAtStatus.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/wexo/module-webshipper/Observer/ExportOrderAtStatus.php b/vendor/wexo/module-webshipper/Observer/ExportOrderAtStatus.php
--- a/vendor/wexo/module-webshipper/Observer/ExportOrderAtStatus.php	
+++ b/vendor/wexo/module-webshipper/Observer/ExportOrderAtStatus.php	(date 1673345299630)
@@ -39,7 +39,9 @@
             if (empty($exportAtOrderStatus) && is_array($exportAtOrderStatus)) {
                 return false;
             }
-
+            if (!is_array($exportAtOrderStatus)) {
+                $exportAtOrderStatus = [$exportAtOrderStatus];
+            }
             $orderStatusIsValid = in_array($order->getStatus(), $exportAtOrderStatus);
             $validShippingMethod = strpos($order->getShippingMethod(), 'webshipper') !== false;
             if ($orderStatusIsValid || !$validShippingMethod) {
```
