### ISSUE TITLE
Carrierr code and Add-ons are missed in magento

### ISSUE THREAD

**Issue by alexvvv** [wexo/module-webshipper#4]
Magento version  2.4.5-p1
Wexo_Webshipper  setup_version=1.0.3 

![изображение](https://github.com/wexo/module-webshipper/assets/5575519/4bb542a8-7572-4cc1-aba6-74873f5be522)

on webshipper we have several droppoint carriers (DAO, GLS), after placing order magento order has info about drop point but no information about carrier code, only method code in format webshipper_X_Y (carrier_code is empty)

also no information about service_code, notifications and addons

is this normal?

**Comment by WebKenth** [comment]
Yes

The webshipper module is meant for communication between magento and webshipper

which is why the rate_id is the identifier for the shipping method 

The webshipper shipping rate has all the information about the carrier and limitations


What do you need the carrier information for?
